@file:Suppress("MagicNumber")

package com.shashluchok.skinwatch.presentation.theme

import androidx.compose.ui.graphics.Color

internal val mdThemeDarkBackground = Color(0xFF0A0C10)
internal val mdThemeDarkOnBackground = Color(0xFFEDEDEF)
internal val mdThemeDarkSurface = Color(0xFF14171D)
internal val mdThemeDarkOnSurface = Color(0xFFEDEDEF)
internal val mdThemeDarkSurfaceContainer = Color(0xFF1D2129)
internal val mdThemeDarkSurfaceContainerHigh = Color(0xFF1D2129)
internal val mdThemeDarkOnSurfaceVariant = Color(0xFF9498A3)
internal val mdThemeDarkOutlineVariant = Color(0xFF2A2F3A)
internal val mdThemeDarkPrimary = Color(0xFFC9A15A)
internal val mdThemeDarkOnPrimary = Color(0xFF14171D)
internal val mdThemeDarkError = Color(0xFFE5555F)
internal val mdThemeDarkOnError = Color(0xFFEDEDEF)

internal val mdThemeDarkPrimaryContainer = Color(0xFF5E4100)
internal val mdThemeDarkOnPrimaryContainer = Color(0xFFFFDEA9)
internal val mdThemeDarkInversePrimary = Color(0xFF795919)
internal val mdThemeDarkSecondary = Color(0xFFC1C6D6)
internal val mdThemeDarkOnSecondary = Color(0xFF2B303C)
internal val mdThemeDarkSecondaryContainer = Color(0xFF414753)
internal val mdThemeDarkOnSecondaryContainer = Color(0xFFDDE2F2)
internal val mdThemeDarkTertiary = Color(0xFFC8C4D6)
internal val mdThemeDarkOnTertiary = Color(0xFF302F3C)
internal val mdThemeDarkTertiaryContainer = Color(0xFF474554)
internal val mdThemeDarkOnTertiaryContainer = Color(0xFFE5E0F2)
internal val mdThemeDarkErrorContainer = Color(0xFF8D1126)
internal val mdThemeDarkOnErrorContainer = Color(0xFFFFDAD9)
internal val mdThemeDarkSurfaceVariant = Color(0xFF424752)
internal val mdThemeDarkOutline = Color(0xFF8C909E)
internal val mdThemeDarkInverseSurface = Color(0xFFE1E2EB)
internal val mdThemeDarkInverseOnSurface = Color(0xFF2E3037)
internal val mdThemeDarkSurfaceDim = Color(0xFF101319)
internal val mdThemeDarkSurfaceBright = Color(0xFF363940)
internal val mdThemeDarkSurfaceContainerLowest = Color(0xFF0B0E14)
internal val mdThemeDarkSurfaceContainerHighest = Color(0xFF32353B)

// --- Light ---
internal val mdThemeLightBackground = Color(0xFFF1F2F5)
internal val mdThemeLightOnBackground = Color(0xFF14171D)
internal val mdThemeLightSurface = Color(0xFFFFFFFF)
internal val mdThemeLightOnSurface = Color(0xFF14171D)
internal val mdThemeLightSurfaceContainer = Color(0xFFFFFFFF)
internal val mdThemeLightSurfaceContainerHigh = Color(0xFFFFFFFF)
internal val mdThemeLightOnSurfaceVariant = Color(0xFF5B606B)
internal val mdThemeLightOutlineVariant = Color(0xFFDCDFE5)
internal val mdThemeLightPrimary = Color(0xFFC9A15A)
internal val mdThemeLightOnPrimary = Color(0xFF14171D)
internal val mdThemeLightError = Color(0xFFB22B3A)
internal val mdThemeLightOnError = Color(0xFFFFFFFF)

internal val mdThemeLightPrimaryContainer = Color(0xFFFFDEA9)
internal val mdThemeLightOnPrimaryContainer = Color(0xFF5E4100)
internal val mdThemeLightInversePrimary = Color(0xFFEBC076)
internal val mdThemeLightSecondary = Color(0xFF595E6C)
internal val mdThemeLightOnSecondary = Color(0xFFFFFFFF)
internal val mdThemeLightSecondaryContainer = Color(0xFFDDE2F2)
internal val mdThemeLightOnSecondaryContainer = Color(0xFF414753)
internal val mdThemeLightTertiary = Color(0xFF5F5D6C)
internal val mdThemeLightOnTertiary = Color(0xFFFFFFFF)
internal val mdThemeLightTertiaryContainer = Color(0xFFE5E0F2)
internal val mdThemeLightOnTertiaryContainer = Color(0xFF474554)
internal val mdThemeLightErrorContainer = Color(0xFFFFDAD9)
internal val mdThemeLightOnErrorContainer = Color(0xFF8D1126)
internal val mdThemeLightSurfaceVariant = Color(0xFFDEE2F1)
internal val mdThemeLightOutline = Color(0xFF727784)
internal val mdThemeLightInverseSurface = Color(0xFF2E3037)
internal val mdThemeLightInverseOnSurface = Color(0xFFEFF0F9)
internal val mdThemeLightSurfaceDim = Color(0xFFD8DAE2)

internal val mdThemeLightSurfaceBright = Color(0xFFFFFFFF)
internal val mdThemeLightSurfaceContainerLowest = Color(0xFFFFFFFF)
internal val mdThemeLightSurfaceContainerHighest = Color(0xFFFFFFFF)

internal val mdThemeScrim = Color(0xFF000000)
internal val mdThemePrimaryFixed = Color(0xFFFFDEA9)
internal val mdThemePrimaryFixedDim = Color(0xFFEBC076)
internal val mdThemeOnPrimaryFixed = Color(0xFF271900)
internal val mdThemeOnPrimaryFixedVariant = Color(0xFF5E4100)
internal val mdThemeSecondaryFixed = Color(0xFFDDE2F2)
internal val mdThemeSecondaryFixedDim = Color(0xFFC1C6D6)
internal val mdThemeOnSecondaryFixed = Color(0xFF161C27)
internal val mdThemeOnSecondaryFixedVariant = Color(0xFF414753)
internal val mdThemeTertiaryFixed = Color(0xFFE5E0F2)
internal val mdThemeTertiaryFixedDim = Color(0xFFC8C4D6)
internal val mdThemeOnTertiaryFixed = Color(0xFF1B1A27)
internal val mdThemeOnTertiaryFixedVariant = Color(0xFF474554)
